#core
xcassets:
  inputs:
    - ../Core/Resources/Assets.xcassets
  outputs:
    - templateName: swift5
      output: ../Core/Resources/Generated/Assets.swift

fonts:
  inputs: ../Core/Resources/Fonts
  outputs:
    templateName: swift5
    output: ../Core/Resources/Generated/Fonts.swift