name: FuzeChallenge
options:
  bundleIdPrefix: com.samuel.FuzeChallenge
  createIntermediateGroups: true

targets:
  Application:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    templates:
      - groupable
    templateAttributes:
      groupName: App
      targetName: Application
    scheme:
      gatherCoverageData: true


targetTemplates:
  groupable:
    sources:
      - path: ${groupName}/${targetName}
    group: ${groupName}
