name: FuzeChallenge
options:
  bundleIdPrefix: com.samuel.FuzeChallenge
  createIntermediateGroups: true

targets:
  Application:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    templates:
      - groupable
    templateAttributes:
      groupName: App
      targetName: Application
    scheme:
      testTargets:
        - name: ServiceTests
          randomExecutionOrder: true
      gatherCoverageData: true
  Core:
    templates:
      - framework
      - groupable
      - swiftgen-generated
    templateAttributes:
      groupName: Core
      targetName: Core
    dependencies:
      - target: Service

  Service:
    templates:
      - framework
      - groupable
      - swiftgen-generated
    scheme:
      gatherCoverageData: true
      testTargets:
        - name: ServiceTests
          randomExecutionOrder: true
    templateAttributes:
      groupName: Service
      targetName: Service

  ServiceTests:
    templates:
      - unit-tests
      - groupable
    templateAttributes:
      groupName: Service
      targetName: ServiceTests
    dependencies:
      - target: Service
      - package: DependencyInjection
      - target: ModuleIntegrator

targetTemplates:
  groupable:
    sources:
      - path: ${groupName}/${targetName}
    group: ${groupName}
  framework:
    deploymentTarget: "14.0"
    platform: iOS
    type: framework
    info:
        path: ${groupName}/${targetName}/Resources/Info.plist
  swiftgen-generated:
    preBuildScripts:
      - script: cd ${groupName}/Config && swiftgen
        name: Swiftgen
        inputFiles:
          - ${groupName}/${targetName}/Resources/Assets.xcassets
          - ${groupName}/${targetName}/Resources/Localizable.strings
          - ${groupName}/${targetName}/Resources/Fonts
        outputFiles:
          - ${groupName}/${targetName}/Resources/Generated/Assets.swift
          - ${groupName}/${targetName}/Resources/Generated/Strings.swift
          - ${groupName}/${targetName}/Resources/Generated/Fonts.swift
  unit-tests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "14.0"
    info:
        path: ${groupName}/${targetName}/Info.plist