name: FuzeChallenge
options:
  bundleIdPrefix: com.samuel.FuzeChallenge
  createIntermediateGroups: true
packages:
  DependencyInjection:
    path: DependencyInjection
  Commons:
    path: Commons
  SDWebImageSwiftUI:
    url: https://github.com/SDWebImage/SDWebImageSwiftUI.git
    from: 2.2.0

targets:
  Application:
    type: application
    templates:
      - groupable
      - commonConfig
    templateAttributes:
      groupName: App
      targetName: Application
    dependencies:
      - target: Core
      - target: ModuleIntegrator
      - target: MatchTracker
      - target: Service
    scheme:
      testTargets:
        - name: ServiceTests
        - name: MatchTrackerTests
          randomExecutionOrder: true
      gatherCoverageData: true

  Core:
    templates:
      - framework
      - groupable
      - swiftgen-generated
      - commonConfig
    templateAttributes:
      groupName: Core
      targetName: Core
    dependencies:
      - target: Service
      - package: DependencyInjection

  ModuleIntegrator:
    templates:
      - framework
      - groupable
      - commonConfig
    templateAttributes:
      groupName: Core
      targetName: ModuleIntegrator
    dependencies:
      - target: Core
      - target: MatchTracker
      - target: Service
      - package: DependencyInjection

  Service:
    templates:
      - framework
      - groupable
      - swiftgen-generated
      - commonConfig
    scheme:
      gatherCoverageData: true
      testTargets:
        - name: ServiceTests
          randomExecutionOrder: true
    templateAttributes:
      groupName: Service
      targetName: Service
    dependencies:
      - package: DependencyInjection

  ServiceTests:
    templates:
      - unit-tests
      - groupable
      - commonConfig
    templateAttributes:
      groupName: Service
      targetName: ServiceTests
    dependencies:
      - target: Service

  MatchTracker:
    templates:
      - framework
      - groupable
      - swiftgen-generated
      - commonConfig
    scheme:
      gatherCoverageData: true
      testTargets:
        - name: MatchTrackerTests
          randomExecutionOrder: true
    templateAttributes:
      groupName: MatchTracker
      targetName: MatchTracker
    dependencies:
      - target: Core
      - target: Service
      - package: DependencyInjection
      - package: Commons
      - package: SDWebImageSwiftUI

  MatchTrackerTests:
    templates:
      - unit-tests
      - groupable
      - commonConfig
    templateAttributes:
      groupName: MatchTracker
      targetName: MatchTrackerTests
    dependencies:
      - target: MatchTracker

targetTemplates:
  commonConfig:
    deploymentTarget: "15.0"
    platform: iOS
  groupable:
    sources:
      - path: ${groupName}/${targetName}
    group: ${groupName}
  framework:
    type: framework
    info:
        path: ${groupName}/${targetName}/Resources/Info.plist
  swiftgen-generated:
    preBuildScripts:
      - script: cd ${groupName}/Config && swiftgen
        name: Swiftgen
        inputFiles:
          - ${groupName}/${targetName}/Resources/Assets.xcassets
          - ${groupName}/${targetName}/Resources/Localizable.strings
          - ${groupName}/${targetName}/Resources/Fonts/
        outputFiles:
          - ${groupName}/${targetName}/Resources/Generated/Assets.swift
          - ${groupName}/${targetName}/Resources/Generated/Strings.swift
          - ${groupName}/${targetName}/Resources/Generated/Fonts.swift
  unit-tests:
    type: bundle.unit-test
    info:
        path: ${groupName}/${targetName}/Info.plist